ame-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  # Unreleased changes
  $CHANGES

change-template: '- $TITLE ([#$NUMBER](https://github.com/2media/policies-builder/pull/$NUMBER)) @$AUTHOR'

categories:
  - title: Added
    labels:
        - 'changelog:added'
  - title: Changed
    labels:
      - 'changelog:changed'
  - title: Deprecated
    labels:
      - 'changelog:deprecated'
  - title: Removed
    labels:
      - 'changelog:removed'
  - title: Fixed
    labels:
      - 'changelog:fixed'
  - title: Security
    labels:
      - 'changelog:security'
  - title: 'Dependency Updates'
    labels:
      - dependencies

exclude-labels:
  - 'skip-changelog'
